"""adding collections

Revision ID: 08c01cf1d868
Revises: d5b2e1093ab5
Create Date: 2025-06-22 05:24:12.278635

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '08c01cf1d868'
down_revision = 'd5b2e1093ab5'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outfits', sa.Column('collection', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_outfits_collection'), 'outfits', ['collection'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_outfits_collection'), table_name='outfits')
    op.drop_column('outfits', 'collection')
    # ### end Alembic commands ### 