"""add some fields sorting system

Revision ID: 21e94fa46dec
Revises: ce15e2d27bcb
Create Date: 2025-06-20 05:01:41.292110

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '21e94fa46dec'
down_revision = 'ce15e2d27bcb'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('items', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('items', 'description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.create_index(op.f('ix_items_article'), 'items', ['article'], unique=False)
    op.create_index(op.f('ix_items_brand'), 'items', ['brand'], unique=False)
    op.create_index(op.f('ix_items_category'), 'items', ['category'], unique=False)
    op.create_index(op.f('ix_items_price'), 'items', ['price'], unique=False)
    op.create_index(op.f('ix_items_size'), 'items', ['size'], unique=False)
    op.add_column('outfits', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('outfits', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('outfits', 'description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.create_index(op.f('ix_outfits_style'), 'outfits', ['style'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_outfits_style'), table_name='outfits')
    op.alter_column('outfits', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('outfits', 'updated_at')
    op.drop_column('outfits', 'created_at')
    op.drop_index(op.f('ix_items_size'), table_name='items')
    op.drop_index(op.f('ix_items_price'), table_name='items')
    op.drop_index(op.f('ix_items_category'), table_name='items')
    op.drop_index(op.f('ix_items_brand'), table_name='items')
    op.drop_index(op.f('ix_items_article'), table_name='items')
    op.alter_column('items', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('items', 'updated_at')
    op.drop_column('items', 'created_at')
    # ### end Alembic commands ### 