"""item images

Revision ID: 3bea85b552fc
Revises: af626e73f025
Create Date: 2025-06-21 10:40:57.410250

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '3bea85b552fc'
down_revision = 'af626e73f025'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 