"""Refactor models

Revision ID: 3ccaad8377c3
Revises: f4a3aef1c9b7
Create Date: 2025-06-22 07:00:32.479988

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '3ccaad8377c3'
down_revision = 'f4a3aef1c9b7'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brands_id'), 'brands', ['id'], unique=False)
    op.create_index(op.f('ix_brands_name'), 'brands', ['name'], unique=True)
    op.create_table('colors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_colors_id'), 'colors', ['id'], unique=False)
    op.create_index(op.f('ix_colors_name'), 'colors', ['name'], unique=True)
    op.create_table('outfit_items',
    sa.Column('outfit_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('item_category', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['outfit_id'], ['outfits.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('outfit_id', 'item_id')
    )
    op.create_table('user_favorite_brands',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'brand_id')
    )
    op.create_table('user_favorite_colors',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('color_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['color_id'], ['colors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'color_id')
    )
    op.drop_table('outfit_footwear_association')
    op.drop_table('outfit_accessories_association')
    op.drop_table('outfit_bottom_association')
    op.drop_table('outfit_top_association')
    op.drop_table('outfit_fragrances_association')
    op.drop_index(op.f('ix_items_size'), table_name='items')
    op.drop_column('items', 'image_url')
    op.drop_column('items', 'size')
    op.drop_column('items', 'color')
    op.drop_column('users', 'favorite_brands')
    op.drop_column('users', 'favorite_colors')
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('favorite_colors', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('favorite_brands', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('items', sa.Column('color', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('items', sa.Column('size', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('items', sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_items_size'), 'items', ['size'], unique=False)
    op.create_table('outfit_fragrances_association',
    sa.Column('outfit_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], name=op.f('outfit_fragrances_association_item_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['outfit_id'], ['outfits.id'], name=op.f('outfit_fragrances_association_outfit_id_fkey'), ondelete='CASCADE')
    )
    op.create_table('outfit_top_association',
    sa.Column('outfit_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], name=op.f('outfit_top_association_item_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['outfit_id'], ['outfits.id'], name=op.f('outfit_top_association_outfit_id_fkey'), ondelete='CASCADE')
    )
    op.create_table('outfit_bottom_association',
    sa.Column('outfit_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], name=op.f('outfit_bottom_association_item_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['outfit_id'], ['outfits.id'], name=op.f('outfit_bottom_association_outfit_id_fkey'), ondelete='CASCADE')
    )
    op.create_table('outfit_accessories_association',
    sa.Column('outfit_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], name=op.f('outfit_accessories_association_item_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['outfit_id'], ['outfits.id'], name=op.f('outfit_accessories_association_outfit_id_fkey'), ondelete='CASCADE')
    )
    op.create_table('outfit_footwear_association',
    sa.Column('outfit_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], name=op.f('outfit_footwear_association_item_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['outfit_id'], ['outfits.id'], name=op.f('outfit_footwear_association_outfit_id_fkey'), ondelete='CASCADE')
    )
    op.drop_table('user_favorite_colors')
    op.drop_table('user_favorite_brands')
    op.drop_table('outfit_items')
    op.drop_index(op.f('ix_colors_name'), table_name='colors')
    op.drop_index(op.f('ix_colors_id'), table_name='colors')
    op.drop_table('colors')
    op.drop_index(op.f('ix_brands_name'), table_name='brands')
    op.drop_index(op.f('ix_brands_id'), table_name='brands')
    op.drop_table('brands')
    # ### end Alembic commands ### 