"""profile and outfit details

Revision ID: 64b4320dd5e9
Revises: 20250619_0001
Create Date: 2025-06-19 09:55:38.871468

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '64b4320dd5e9'
down_revision = '20250619_0001'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_items_id'), 'items', ['id'], unique=False)
    op.add_column('outfits', sa.Column('top_id', sa.Integer(), nullable=True))
    op.add_column('outfits', sa.Column('bottom_id', sa.Integer(), nullable=True))
    op.add_column('outfits', sa.Column('footwear_id', sa.Integer(), nullable=True))
    op.add_column('outfits', sa.Column('accessories_id', sa.Integer(), nullable=True))
    op.add_column('outfits', sa.Column('fragrances_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_outfits_id'), 'outfits', ['id'], unique=False)
    op.create_foreign_key(None, 'outfits', 'items', ['fragrances_id'], ['id'])
    op.create_foreign_key(None, 'outfits', 'items', ['accessories_id'], ['id'])
    op.create_foreign_key(None, 'outfits', 'items', ['footwear_id'], ['id'])
    op.create_foreign_key(None, 'outfits', 'items', ['top_id'], ['id'])
    op.create_foreign_key(None, 'outfits', 'items', ['bottom_id'], ['id'])
    op.add_column('users', sa.Column('avatar', sa.String(), nullable=True))
    op.add_column('users', sa.Column('first_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    op.add_column('users', sa.Column('date_of_birth', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('height', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('weight', sa.Float(), nullable=True))
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('users', 'is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=True)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.alter_column('users', 'is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_column('users', 'weight')
    op.drop_column('users', 'height')
    op.drop_column('users', 'date_of_birth')
    op.drop_column('users', 'phone_number')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    op.drop_column('users', 'avatar')
    op.drop_constraint(None, 'outfits', type_='foreignkey')
    op.drop_constraint(None, 'outfits', type_='foreignkey')
    op.drop_constraint(None, 'outfits', type_='foreignkey')
    op.drop_constraint(None, 'outfits', type_='foreignkey')
    op.drop_constraint(None, 'outfits', type_='foreignkey')
    op.drop_index(op.f('ix_outfits_id'), table_name='outfits')
    op.drop_column('outfits', 'fragrances_id')
    op.drop_column('outfits', 'accessories_id')
    op.drop_column('outfits', 'footwear_id')
    op.drop_column('outfits', 'bottom_id')
    op.drop_column('outfits', 'top_id')
    op.drop_index(op.f('ix_items_id'), table_name='items')
    # ### end Alembic commands ### 