"""Initial schema

Revision ID: 6a67d18521fc
Revises: e1c8d8b82b83
Create Date: 2025-06-23 11:54:18.937585

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '6a67d18521fc'
down_revision = 'e1c8d8b82b83'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 