"""Initial migration

Revision ID: 8ce91692d472
Revises: 3bea85b552fc
Create Date: 2025-06-21 10:50:06.297255

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '8ce91692d472'
down_revision = '3bea85b552fc'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_images_id'), 'item_images', ['id'], unique=False)
    op.create_index(op.f('ix_item_images_item_id'), 'item_images', ['item_id'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_item_images_item_id'), table_name='item_images')
    op.drop_index(op.f('ix_item_images_id'), table_name='item_images')
    op.drop_table('item_images')
    # ### end Alembic commands ### 