"""add_favorites trends history etc

Revision ID: 97a57c925781
Revises: 21e94fa46dec
Create Date: 2025-06-20 05:58:37.256382

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '97a57c925781'
down_revision = '21e94fa46dec'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_favorite_items',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'item_id')
    )
    op.create_table('user_view_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('viewed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_view_history_id'), 'user_view_history', ['id'], unique=False)
    op.create_index(op.f('ix_user_view_history_item_id'), 'user_view_history', ['item_id'], unique=False)
    op.create_index(op.f('ix_user_view_history_user_id'), 'user_view_history', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_view_history_viewed_at'), 'user_view_history', ['viewed_at'], unique=False)
    op.add_column('items', sa.Column('style', sa.String(length=50), nullable=True))
    op.add_column('items', sa.Column('collection', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_items_collection'), 'items', ['collection'], unique=False)
    op.create_index(op.f('ix_items_style'), 'items', ['style'], unique=False)
    op.add_column('users', sa.Column('chest', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('waist', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('hips', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('favorite_colors', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('favorite_brands', sa.Text(), nullable=True))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'favorite_brands')
    op.drop_column('users', 'favorite_colors')
    op.drop_column('users', 'hips')
    op.drop_column('users', 'waist')
    op.drop_column('users', 'chest')
    op.drop_index(op.f('ix_items_style'), table_name='items')
    op.drop_index(op.f('ix_items_collection'), table_name='items')
    op.drop_column('items', 'collection')
    op.drop_column('items', 'style')
    op.drop_index(op.f('ix_user_view_history_viewed_at'), table_name='user_view_history')
    op.drop_index(op.f('ix_user_view_history_user_id'), table_name='user_view_history')
    op.drop_index(op.f('ix_user_view_history_item_id'), table_name='user_view_history')
    op.drop_index(op.f('ix_user_view_history_id'), table_name='user_view_history')
    op.drop_table('user_view_history')
    op.drop_table('user_favorite_items')
    # ### end Alembic commands ### 