"""add some fileds article sixe abd multiple choice

Revision ID: ce15e2d27bcb
Revises: 64b4320dd5e9
Create Date: 2025-06-20 04:42:02.772688

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'ce15e2d27bcb'
down_revision = '64b4320dd5e9'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outfit_accessories_association',
    sa.Column('outfit_id', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['outfit_id'], ['outfits.id'], )
    )
    op.create_table('outfit_bottom_association',
    sa.Column('outfit_id', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['outfit_id'], ['outfits.id'], )
    )
    op.create_table('outfit_footwear_association',
    sa.Column('outfit_id', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['outfit_id'], ['outfits.id'], )
    )
    op.create_table('outfit_fragrances_association',
    sa.Column('outfit_id', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['outfit_id'], ['outfits.id'], )
    )
    op.create_table('outfit_top_association',
    sa.Column('outfit_id', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['outfit_id'], ['outfits.id'], )
    )
    op.add_column('items', sa.Column('article', sa.String(), nullable=True))
    op.add_column('items', sa.Column('size', sa.String(), nullable=True))
    op.drop_constraint(op.f('outfits_bottom_id_fkey'), 'outfits', type_='foreignkey')
    op.drop_constraint(op.f('outfits_footwear_id_fkey'), 'outfits', type_='foreignkey')
    op.drop_constraint(op.f('outfits_accessories_id_fkey'), 'outfits', type_='foreignkey')
    op.drop_constraint(op.f('outfits_top_id_fkey'), 'outfits', type_='foreignkey')
    op.drop_constraint(op.f('outfits_fragrances_id_fkey'), 'outfits', type_='foreignkey')
    op.drop_column('outfits', 'accessories_id')
    op.drop_column('outfits', 'bottom_id')
    op.drop_column('outfits', 'fragrances_id')
    op.drop_column('outfits', 'footwear_id')
    op.drop_column('outfits', 'top_id')
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outfits', sa.Column('top_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('outfits', sa.Column('footwear_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('outfits', sa.Column('fragrances_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('outfits', sa.Column('bottom_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('outfits', sa.Column('accessories_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('outfits_fragrances_id_fkey'), 'outfits', 'items', ['fragrances_id'], ['id'])
    op.create_foreign_key(op.f('outfits_top_id_fkey'), 'outfits', 'items', ['top_id'], ['id'])
    op.create_foreign_key(op.f('outfits_accessories_id_fkey'), 'outfits', 'items', ['accessories_id'], ['id'])
    op.create_foreign_key(op.f('outfits_footwear_id_fkey'), 'outfits', 'items', ['footwear_id'], ['id'])
    op.create_foreign_key(op.f('outfits_bottom_id_fkey'), 'outfits', 'items', ['bottom_id'], ['id'])
    op.drop_column('items', 'size')
    op.drop_column('items', 'article')
    op.drop_table('outfit_top_association')
    op.drop_table('outfit_fragrances_association')
    op.drop_table('outfit_footwear_association')
    op.drop_table('outfit_bottom_association')
    op.drop_table('outfit_accessories_association')
    # ### end Alembic commands ### 