"""add auth fields

Revision ID: e1a6b1bde756
Revises: 97a57c925781
Create Date: 2025-06-20 11:54:53.966440

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'e1a6b1bde756'
down_revision = '97a57c925781'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 