"""Add cart reservation fields

Revision ID: e1c8d8b82b83
Revises: 5e6e02c20aa8
Create Date: 2025-06-23 11:03:31.556732

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'e1c8d8b82b83'
down_revision = '5e6e02c20aa8'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outfit_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('outfit_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=False),
    sa.Column('thumbnail_url', sa.String(length=255), nullable=True),
    sa.Column('alt_text', sa.String(length=255), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['outfit_id'], ['outfits.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outfit_images_id'), 'outfit_images', ['id'], unique=False)
    op.create_index(op.f('ix_outfit_images_outfit_id'), 'outfit_images', ['outfit_id'], unique=False)
    op.create_table('variant_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=False),
    sa.Column('thumbnail_url', sa.String(length=255), nullable=True),
    sa.Column('alt_text', sa.String(length=255), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['variant_id'], ['item_variants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_variant_images_id'), 'variant_images', ['id'], unique=False)
    op.create_index(op.f('ix_variant_images_variant_id'), 'variant_images', ['variant_id'], unique=False)
    op.add_column('cart_items', sa.Column('is_reserved', sa.Integer(), nullable=True))
    op.add_column('cart_items', sa.Column('reserved_until', sa.DateTime(timezone=True), nullable=True))
    op.add_column('cart_items', sa.Column('price_at_time', sa.Float(), nullable=True))
    op.add_column('cart_items', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('cart_items', sa.Column('notes', sa.String(length=255), nullable=True))
    op.add_column('comments', sa.Column('text', sa.Text(), nullable=False))
    op.add_column('comments', sa.Column('is_approved', sa.Boolean(), nullable=True))
    op.add_column('comments', sa.Column('is_edited', sa.Boolean(), nullable=True))
    op.add_column('comments', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.add_column('comments', sa.Column('display_name', sa.String(length=100), nullable=True))
    op.add_column('comments', sa.Column('is_anonymous', sa.Boolean(), nullable=True))
    op.alter_column('comments', 'rating',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.create_index(op.f('ix_comments_parent_id'), 'comments', ['parent_id'], unique=False)
    op.create_foreign_key(None, 'comments', 'comments', ['parent_id'], ['id'], ondelete='CASCADE')
    op.drop_column('comments', 'content')
    op.add_column('item_images', sa.Column('thumbnail_url', sa.String(length=255), nullable=True))
    op.add_column('item_images', sa.Column('alt_text', sa.String(length=255), nullable=True))
    op.add_column('item_images', sa.Column('order', sa.Integer(), nullable=True))
    op.add_column('item_images', sa.Column('is_primary', sa.Boolean(), nullable=True))
    op.add_column('item_images', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.drop_column('item_images', 'position')
    op.add_column('item_variants', sa.Column('barcode', sa.String(length=50), nullable=True))
    op.add_column('item_variants', sa.Column('reserved_stock', sa.Integer(), nullable=False))
    op.add_column('item_variants', sa.Column('min_stock_level', sa.Integer(), nullable=True))
    op.add_column('item_variants', sa.Column('discount_price', sa.Float(), nullable=True))
    op.add_column('item_variants', sa.Column('weight', sa.Float(), nullable=True))
    op.add_column('item_variants', sa.Column('dimensions', sa.JSON(), nullable=True))
    op.add_column('item_variants', sa.Column('attributes', sa.JSON(), nullable=True))
    op.add_column('item_variants', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('item_variants', sa.Column('is_default', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_item_variants_barcode'), 'item_variants', ['barcode'], unique=True)
    op.add_column('items', sa.Column('base_price', sa.Float(), nullable=True))
    op.add_column('items', sa.Column('subcategory', sa.String(length=50), nullable=True))
    op.add_column('items', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('items', sa.Column('tags', sa.JSON(), nullable=True))
    op.add_column('items', sa.Column('attributes', sa.JSON(), nullable=True))
    op.add_column('items', sa.Column('meta_title', sa.String(length=255), nullable=True))
    op.add_column('items', sa.Column('meta_description', sa.Text(), nullable=True))
    op.add_column('items', sa.Column('slug', sa.String(length=255), nullable=True))
    op.drop_index(op.f('ix_items_color'), table_name='items')
    op.drop_index(op.f('ix_items_price'), table_name='items')
    op.drop_index(op.f('ix_items_size'), table_name='items')
    op.drop_index(op.f('ix_items_article'), table_name='items')
    op.create_index(op.f('ix_items_article'), 'items', ['article'], unique=True)
    op.create_index(op.f('ix_items_base_price'), 'items', ['base_price'], unique=False)
    op.create_index(op.f('ix_items_is_active'), 'items', ['is_active'], unique=False)
    op.create_index(op.f('ix_items_slug'), 'items', ['slug'], unique=True)
    op.create_index(op.f('ix_items_subcategory'), 'items', ['subcategory'], unique=False)
    op.drop_column('items', 'color')
    op.drop_column('items', 'size')
    op.drop_column('items', 'image_url')
    op.drop_column('items', 'price')
    op.add_column('outfit_items', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('outfit_items', sa.Column('variant_id', sa.Integer(), nullable=True))
    op.add_column('outfit_items', sa.Column('notes', sa.String(length=255), nullable=True))
    op.add_column('outfit_items', sa.Column('order', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_outfit_items_id'), 'outfit_items', ['id'], unique=False)
    op.create_foreign_key(None, 'outfit_items', 'item_variants', ['variant_id'], ['id'], ondelete='SET NULL')
    op.add_column('outfits', sa.Column('outfit_type', sa.String(length=50), nullable=True))
    op.add_column('outfits', sa.Column('is_public', sa.Boolean(), nullable=True))
    op.add_column('outfits', sa.Column('is_featured', sa.Boolean(), nullable=True))
    op.add_column('outfits', sa.Column('tags', sa.JSON(), nullable=True))
    op.add_column('outfits', sa.Column('season', sa.String(length=50), nullable=True))
    op.add_column('outfits', sa.Column('occasion', sa.String(length=100), nullable=True))
    op.add_column('outfits', sa.Column('slug', sa.String(length=255), nullable=True))
    op.add_column('outfits', sa.Column('meta_title', sa.String(length=255), nullable=True))
    op.add_column('outfits', sa.Column('meta_description', sa.Text(), nullable=True))
    op.add_column('outfits', sa.Column('views_count', sa.Integer(), nullable=True))
    op.add_column('outfits', sa.Column('likes_count', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_outfits_is_featured'), 'outfits', ['is_featured'], unique=False)
    op.create_index(op.f('ix_outfits_is_public'), 'outfits', ['is_public'], unique=False)
    op.create_index(op.f('ix_outfits_outfit_type'), 'outfits', ['outfit_type'], unique=False)
    op.create_index(op.f('ix_outfits_slug'), 'outfits', ['slug'], unique=True)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_outfits_slug'), table_name='outfits')
    op.drop_index(op.f('ix_outfits_outfit_type'), table_name='outfits')
    op.drop_index(op.f('ix_outfits_is_public'), table_name='outfits')
    op.drop_index(op.f('ix_outfits_is_featured'), table_name='outfits')
    op.drop_column('outfits', 'likes_count')
    op.drop_column('outfits', 'views_count')
    op.drop_column('outfits', 'meta_description')
    op.drop_column('outfits', 'meta_title')
    op.drop_column('outfits', 'slug')
    op.drop_column('outfits', 'occasion')
    op.drop_column('outfits', 'season')
    op.drop_column('outfits', 'tags')
    op.drop_column('outfits', 'is_featured')
    op.drop_column('outfits', 'is_public')
    op.drop_column('outfits', 'outfit_type')
    op.drop_constraint(None, 'outfit_items', type_='foreignkey')
    op.drop_index(op.f('ix_outfit_items_id'), table_name='outfit_items')
    op.drop_column('outfit_items', 'order')
    op.drop_column('outfit_items', 'notes')
    op.drop_column('outfit_items', 'variant_id')
    op.drop_column('outfit_items', 'id')
    op.add_column('items', sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('items', sa.Column('image_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('items', sa.Column('size', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('items', sa.Column('color', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_items_subcategory'), table_name='items')
    op.drop_index(op.f('ix_items_slug'), table_name='items')
    op.drop_index(op.f('ix_items_is_active'), table_name='items')
    op.drop_index(op.f('ix_items_base_price'), table_name='items')
    op.drop_index(op.f('ix_items_article'), table_name='items')
    op.create_index(op.f('ix_items_article'), 'items', ['article'], unique=False)
    op.create_index(op.f('ix_items_size'), 'items', ['size'], unique=False)
    op.create_index(op.f('ix_items_price'), 'items', ['price'], unique=False)
    op.create_index(op.f('ix_items_color'), 'items', ['color'], unique=False)
    op.drop_column('items', 'slug')
    op.drop_column('items', 'meta_description')
    op.drop_column('items', 'meta_title')
    op.drop_column('items', 'attributes')
    op.drop_column('items', 'tags')
    op.drop_column('items', 'is_active')
    op.drop_column('items', 'subcategory')
    op.drop_column('items', 'base_price')
    op.drop_index(op.f('ix_item_variants_barcode'), table_name='item_variants')
    op.drop_column('item_variants', 'is_default')
    op.drop_column('item_variants', 'is_active')
    op.drop_column('item_variants', 'attributes')
    op.drop_column('item_variants', 'dimensions')
    op.drop_column('item_variants', 'weight')
    op.drop_column('item_variants', 'discount_price')
    op.drop_column('item_variants', 'min_stock_level')
    op.drop_column('item_variants', 'reserved_stock')
    op.drop_column('item_variants', 'barcode')
    op.add_column('item_images', sa.Column('position', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('item_images', 'created_at')
    op.drop_column('item_images', 'is_primary')
    op.drop_column('item_images', 'order')
    op.drop_column('item_images', 'alt_text')
    op.drop_column('item_images', 'thumbnail_url')
    op.add_column('comments', sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_index(op.f('ix_comments_parent_id'), table_name='comments')
    op.alter_column('comments', 'rating',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_column('comments', 'is_anonymous')
    op.drop_column('comments', 'display_name')
    op.drop_column('comments', 'parent_id')
    op.drop_column('comments', 'is_edited')
    op.drop_column('comments', 'is_approved')
    op.drop_column('comments', 'text')
    op.drop_column('cart_items', 'notes')
    op.drop_column('cart_items', 'updated_at')
    op.drop_column('cart_items', 'price_at_time')
    op.drop_column('cart_items', 'reserved_until')
    op.drop_column('cart_items', 'is_reserved')
    op.drop_index(op.f('ix_variant_images_variant_id'), table_name='variant_images')
    op.drop_index(op.f('ix_variant_images_id'), table_name='variant_images')
    op.drop_table('variant_images')
    op.drop_index(op.f('ix_outfit_images_outfit_id'), table_name='outfit_images')
    op.drop_index(op.f('ix_outfit_images_id'), table_name='outfit_images')
    op.drop_table('outfit_images')
    # ### end Alembic commands ### 