"""Эupdates business logic

Revision ID: ed95a3c05ef3
Revises: 08c01cf1d868
Create Date: 2025-06-22 05:40:04.652275

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'ed95a3c05ef3'
down_revision = '08c01cf1d868'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_variants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('size', sa.String(length=20), nullable=True),
    sa.Column('color', sa.String(length=30), nullable=True),
    sa.Column('sku', sa.String(length=50), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_variants_color'), 'item_variants', ['color'], unique=False)
    op.create_index(op.f('ix_item_variants_id'), 'item_variants', ['id'], unique=False)
    op.create_index(op.f('ix_item_variants_item_id'), 'item_variants', ['item_id'], unique=False)
    op.create_index(op.f('ix_item_variants_size'), 'item_variants', ['size'], unique=False)
    op.create_index(op.f('ix_item_variants_sku'), 'item_variants', ['sku'], unique=True)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_item_variants_sku'), table_name='item_variants')
    op.drop_index(op.f('ix_item_variants_size'), table_name='item_variants')
    op.drop_index(op.f('ix_item_variants_item_id'), table_name='item_variants')
    op.drop_index(op.f('ix_item_variants_id'), table_name='item_variants')
    op.drop_index(op.f('ix_item_variants_color'), table_name='item_variants')
    op.drop_table('item_variants')
    # ### end Alembic commands ### 