"""add constraints to cart_items table

Revision ID: f4a3aef1c9b7
Revises: ed95a3c05ef3
Create Date: 2025-06-22 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'f4a3aef1c9b7'
down_revision = 'ed95a3c05ef3'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_cart_user_item', 'cart_items', ['user_id', 'item_id'])
    op.create_check_constraint('ck_cart_quantity_positive', 'cart_items', sa.text('quantity > 0'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_cart_quantity_positive', 'cart_items', type_='check')
    op.drop_constraint('uq_cart_user_item', 'cart_items', type_='unique')
    # ### end Alembic commands ### 